version: '3.8'

services:
  cweb:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080" # Expose port 8080
    volumes:
      - ./modules:/app/modules