#ifndef CWEB_CONFIG_H
#define CWEB_CONFIG_H

#define MAX_ROUTES 10
#define MAX_WEBSOCKETS 10
#define MAX_JOBS 10

#define ROUTER_MAX_MODULES 100
#define SO_PATH_MAX_LEN 256

#define REQUEST_BUFFER_SIZE (8 * 1024)

#define DEFAULT_PORT 8080
#define DEFAULT_DEV_THREAD_POOL_SIZE 4
#define DEFAULT_PROD_THREAD_POOL_MULTIPLIER 2

#endif // CWEB_CONFIG_H
